[tool.pydocstyle]
ignore = [
    "D100",
    "D101",
    "D102",
    "D103",
    "D105",
    "D106",
    "D107",
    "D200",
    "D202",
    "D203",
    "D205",
    "D211",
    "D212",
    "D213",
    "D301",
    "D400",
]
